### ISSUE TITLE
Wrong version is published

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/npm-packager#69] opened 2023-10-06 18:09 UTC
### Describe the bug

I have installed @deep-foundation/capacitor-device 10.0.1 , changed some links and tried to publish it as `10.0.2-dev.0` but instead 18.0.0 version was published because the latest version of npm package is [18.0.0-dev.23](https://www.npmjs.com/package/@deep-foundation/capacitor-device/v/18.0.0-dev.23)
![image](https://github.com/deep-foundation/npm-packager/assets/66206278/f63ceea0-b5e1-495d-b077-2aa76da2ffe0)
![image](https://github.com/deep-foundation/npm-packager/assets/66206278/3b92f916-5d72-41b9-a3ba-f7772a00f5d1)

**Comment by Konard** [comment] 2023-10-06 18:17
This is duplicate of https://github.com/deep-foundation/npm-packager/issues/65

**Closed by Konard** 2023-10-06 18:17 UTC
Labels: bug
